# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week3App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week3App

  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'

#import <Reachability/Reachability.h>
end
